const form=document.querySelector('#compare-form'),picker=document.querySelector('#model-picker'),promptBox=document.querySelector('#prompt'),runButton=document.querySelector('#run-button'),runSection=document.querySelector('#run-section'),grid=document.querySelector('#result-grid'),progress=document.querySelector('#progress'),comparison=document.querySelector('#comparison'),errorBox=document.querySelector('#form-error'),historyList=document.querySelector('#history-list');
const HISTORY_KEY='model-fomo-recent-v1', MAX_HISTORY=6;
let config;
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const selected=()=>[...picker.querySelectorAll('select')].map(s=>s.value).filter(Boolean);
function updateSelection(){const models=selected(),count=models.length;document.querySelector('#selection-count').textContent=`${count} selected`;picker.querySelectorAll('select').forEach(select=>[...select.options].forEach(option=>{option.disabled=Boolean(option.value&&option.value!==select.value&&models.includes(option.value))}));runButton.disabled=count===0||new Set(models).size!==count;}
function pendingCard(model){return `<article class="card" id="card-${CSS.escape(model)}"><div class="card-head"><h3>${esc(model)}</h3><span class="badge running">Running</span></div><div class="metrics"><span>Latency —</span><span>Tokens —</span></div><div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton" style="width:60%"></div></div></article>`}
function renderResult(r){const card=document.getElementById(`card-${CSS.escape(r.model)}`), cls=r.status.toLowerCase().replaceAll(' ','-'), latency=r.latency_seconds==null?'n/a':`${r.latency_seconds.toFixed(2)}s`, usage=r.prompt_tokens==null&&r.completion_tokens==null?'Tokens n/a':`In ${r.prompt_tokens??'n/a'} · Out ${r.completion_tokens??'n/a'}`;card.innerHTML=`<div class="card-head"><h3>${esc(r.model)}</h3><span class="badge ${cls}">${esc(r.status)}</span></div><div class="metrics"><span>${latency}</span><span>${usage}</span></div>${r.answer?`<div class="answer">${esc(r.answer)}</div><button class="copy" type="button">Copy response</button>`:`<div class="empty">${esc(r.error||'No usable answer was returned.')}</div>`}`;if(r.answer)card.querySelector('.copy').onclick=async e=>{await navigator.clipboard.writeText(r.answer);e.target.textContent='Copied';setTimeout(()=>e.target.textContent='Copy response',1200)};}
function renderComparison(c){comparison.hidden=false;comparison.innerHTML=`<p class="eyebrow">COMBINED COMPARISON</p><h2>What happened in this run</h2><div class="compare-metrics"><div><small>Fastest successful model</small><strong>${c.fastest_model?`${esc(c.fastest_model)} · ${c.fastest_seconds.toFixed(2)}s`:'Not available'}</strong></div><div><small>Shortest successful output</small><strong>${c.shortest_model?`${esc(c.shortest_model)} · ${c.shortest_output_tokens} tokens`:'Not available'}</strong></div></div><p class="recommendation">${esc(c.recommendation)}</p>`;}
function saveHistory(prompt,models,statuses){const items=readHistory();items.unshift({prompt,models,timestamp:new Date().toISOString(),statuses});localStorage.setItem(HISTORY_KEY,JSON.stringify(items.slice(0,MAX_HISTORY)));renderHistory();}
function readHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return []}}
function renderHistory(){const items=readHistory();historyList.innerHTML=items.length?items.map(i=>`<div class="history-item"><time datetime="${esc(i.timestamp)}">${new Date(i.timestamp).toLocaleString()}</time><div class="history-prompt" title="${esc(i.prompt)}">${esc(i.prompt)}</div><div class="history-status">${i.models.map((m,n)=>`${esc(m)}: ${esc(i.statuses[n]||'Unknown')}`).join(' · ')}</div></div>`).join(''):'<div class="history-empty">Your completed comparisons will appear here. Nothing is sent to a history database.</div>';}
async function start(){try{config=await fetch('/api/config').then(r=>r.json());picker.innerHTML=Array.from({length:config.max_selected},(_,slot)=>`<label class="model-select"><span>Model ${slot+1}</span><select aria-label="Model ${slot+1}"><option value="">No model</option>${config.models.map(m=>`<option value="${esc(m)}" ${config.defaults[slot]===m?'selected':''}>${esc(config.model_labels?.[m]||m)}</option>`).join('')}</select></label>`).join('');document.querySelector('#cutoff-note').textContent=`Each model gets up to ${config.timeout_seconds} seconds. Failed and timed-out models will not block the comparison.`;picker.addEventListener('change',updateSelection);updateSelection()}catch{errorBox.textContent='Could not load model configuration.'}renderHistory()}
form.addEventListener('submit',async e=>{e.preventDefault();const models=selected(), prompt=promptBox.value.trim();if(!prompt||!models.length)return;runButton.disabled=true;errorBox.textContent='';runSection.hidden=false;comparison.hidden=true;grid.innerHTML=models.map(pendingCard).join('');progress.textContent=`0 of ${models.length} finished`;runSection.scrollIntoView({behavior:'smooth',block:'start'});const statuses={},decoder=new TextDecoder();let buffer='',done=0;try{const response=await fetch('/api/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,models})});if(!response.ok){const body=await response.json();throw new Error(body.error||'Comparison could not start.')}const reader=response.body.getReader();while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.type==='result'){renderResult(event.result);statuses[event.result.model]=event.result.status;done++;progress.textContent=`${done} of ${models.length} finished`}else if(event.type==='comparison')renderComparison(event.comparison)}}saveHistory(prompt,models,models.map(m=>statuses[m]||'Failed'))}catch(err){errorBox.textContent=err.message;progress.textContent='Comparison stopped'}finally{runButton.disabled=false;updateSelection()}});
document.querySelector('#clear-history').onclick=()=>{localStorage.removeItem(HISTORY_KEY);renderHistory()};start();
